### DISCUSSION TITLE
Istio and cryostat

### DISCUSSION THREAD

**Discussion by grzesuav** [cryostatio/cryostat#617] [Q&A]
Hi,
I wonder is there is any recommendation/example of running istio along with cryostat.

In our clusters most workloads are istio-enabled, for testing purposes I have disabled istio injection for cryostat pod, and allowed via `PeerAuthentication` access to target workload
```yaml
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: xxx
  namespace: yyy
spec:
  mtls:
    mode: PERMISSIVE
  selector:
    matchLabels:
      app: {{ .Values.apps.service.name }}
```

however in final setup I would like to keep it in istio, if possible.

So I am looking or advise/example how to configure it, or it won't work for some reason (like jmx connections)?
