### ISSUE TITLE
[Request] Default recording name

### ISSUE THREAD

**Issue by grzesuav** [cryostatio/cryostat#635]
### Describe the feature

Would be great if the `name`  of new recording could default to `namespace_pod_start_time` instead of empty, or even better - to set a default template using labels / cryostat annotations as they are present - `{{NAMESPACE}}_{{POD_NAME}}_{{current_time}}`
<img width="820" alt="image" src="https://github.com/user-attachments/assets/740b726d-a154-4690-b6fc-edb7274664ad">

Cryostat annotations 
<img width="422" alt="image" src="https://github.com/user-attachments/assets/08a76cb7-7066-4f74-8b2e-6fc95273fc2b">

**Comment by andrewazores** [comment]
Those labels and annotations are only present/make sense to use in the case that Cryostat is deployed in a Kubernetes environment, and that the target application you're looking at was discovered via its built-in Kubernetes API Endpoints mechanism. Any default name applied here would need to be somehow genericized so that it would either be applicable in all cases (deployed in Docker Swarm, or using the Cryostat Agent where the Namespace annotation would not be present, etc.), or else somehow this default naming scheme needs to be dependent on which of those attributes are actually available at runtime, or dependent on the discovery mechanism that produces this target application record.

Perhaps simply generating a semi-randomized name and instead including these various optional attributes as recording labels could be another solution to this problem?

Related to https://github.com/cryostatio/cryostat/issues/41

**Comment by grzesuav** [comment]
got it, make sense for me. Actually in case of using cryistat agent, what metadata is exposed ? I probably will test this approach soon, I wonder how many metadata we can attach from k8s

**Comment by andrewazores** [comment]
The Cryostat Agent is also designed to be rather generic and isn't very aware of whether it is running in Kubernetes, or in a container at all for that matter. It does know how to look for a serviceaccount token file that Kubernetes may mount, but that is the extend of its integration to Kubernetes. It doesn't have anything like a Kubernetes client, so it is unable to determine its own Namespace, Pod name, or anything else like that.

When you set up the Cryostat Agent on your application Deployment, you must configure the Agent's Callback URL:

https://cryostat.io/get-started/#using-the-cryostat-agent

```
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CRYOSTAT_AGENT_CALLBACK
              # This infers the Agent Callback directly from the Pod's IP address using the
              # Kubernetes Downward API. Use this value directly as provided. The port number
              # 9977 can be changed but must match the containerPort below.
              value: "http://$(POD_IP):9977"
              # Replace "abcd1234" with a base64-encoded authentication token. For example,
              # in your terminal, do 'oc whoami -t | base64' to use your user account's
              # token as the token that the Agent will pass to authorize itself with
              # the Cryostat server.
```

Rather than using the Downward API to expose the `POD_IP`, you could probably instead inject other [Kubernetes Pod DNS](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pods) values into environment variables, then configure the Callback URL to reference these instead of the raw cluster-internal IP address. This way, when your Agent instances register with Cryostat, the target connection URL could include your pod name and namespace.
